name: ghas-enablement-status
description: Start a checkrun for a given workflow

author: vionix

branding:
  icon: anchor
  color: blue

inputs:
  github-token:
    description: "the token for the repo"
    required: true

outputs:
  checkrun-id:
    description: "The ID of the checkrun created"
    value: ${{ steps.ghas-status.outputs.checkrun-id }}

runs:
  using: composite
  steps:
    - name: Check if GHAS is enabled
      uses: actions/github-script@v7
      id: status
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          const response = await github.rest.repos.get({
            owner: '${{ github.repository_owner }}',
            repo: '${{ github.event.repository.name }}'
          });
          console.log(`Response data from rest repos get ${JSON.stringify(response.data)}`)
          const securityEnabled = response.data.security_and_analysis?.advanced_security?.status === 'enabled';
          core.setOutput('enabled', securityEnabled);
          
          if (!securityEnabled) {
            const message = 'GitHub Advanced Security is NOT enabled.';
            core.warning(message);

          } else {
            const message = 'GitHub Advanced Security is enabled!';
            core.notice(message);
          }
          return securityEnabled;

    - name: Print all the results from the check
      shell: bash
      run: |
        echo ${{ toJSON(steps.status.outputs) }}
