name: ghas-enablement-status
description: Start a checkrun for a given workflow

author: vionix

branding:
  icon: anchor
  color: blue

inputs:
  github-token:
    description: "the token for the repo"
    required: true
  github-enterprise:
    description: 'Whether or not this is running in github enterprise'
    required: false
    default: "true"

outputs:
  enabled:
    description: "The ID of the checkrun created"
    value: ${{ steps.status.outputs.enabled }}

runs:
  using: composite
  steps:
    - name: Check if GHAS is enabled
      uses: actions/github-script@v7
      id: status
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          const response = await github.rest.repos.get({
            owner: '${{ github.repository_owner }}',
            repo: '${{ github.event.repository.name }}'
          });

          console.debug(`Response data from rest repos get '${JSON.stringify(response.data.security_and_analysis)}'`)
          const securityEnabled = response.data.security_and_analysis?.advanced_security?.status === 'enabled';
          core.setOutput('enabled', securityEnabled);
          
          if (securityEnabled) {
            const message = '✅ GitHub Advanced Security is enabled at this Github repository (${{ github.repository }})!';
            core.notice(message);

          } else {
            const message = '❌ GitHub Advanced Security is NOT enabled.';
            core.warning(message);
          }

          // Adds an output called result, but that doesn't add good context
          // return securityEnabled;

    - name: Print all the results from the check
      shell: bash
      run: |
        echo '${{ toJSON(steps.status.outputs) }}'
