name: sbom-generator
description: Generates the SBOM report for a given docker image to md file, workflow summary and PR comment

inputs:
  git-revision:
    description: 'The reference to the git sha'
    required: true

  docker-image-repo-tag:
    description: 'The full docker image repo:tag'
    required: true

  syft-docker-image-tag:
    description: 'The json object to print'
    required: false
    default: dockerhub.docker.artifactory.viasat.com/anchore/syft:v1.3.0
  
  add-comment-to-current-pr:
    description: 'The json object to print'
    required: false
    default: 'false'
  
outputs:
  sbom-report-file-path:
    description: The path where the reports are located
    value: ${{ steps.report-generator.outputs.sbom-report-file-path }}
  sbom-report-value:
    description: The value of the report
    value: ${{ steps.report-generator.outputs.sbom-report-value }}

runs:
  using: "composite"
  steps:
    - name: Make sure to pull the docker image ${{ inputs.docker-image-repo-tag }} before
      shell: bash
      run: docker pull ${{ inputs.docker-image-repo-tag }}

    - name: Annotate Job with current information with SBOM
      id: report-generator
      shell: bash
      run: |
        echo "# :jigsaw: SBOM Report" >> simple-sbom-report.md
        echo "" >> simple-sbom-report.md
        echo "## :whale: ${{ inputs.docker-image-repo-tag }}" >> simple-sbom-report.md
        echo "" >> simple-sbom-report.md
        echo "* Revision: ${{ inputs.git-revision }}" >> simple-sbom-report.md
        echo "" >> simple-sbom-report.md

        docker run -v /var/run/docker.sock:/var/run/docker.sock ${{ inputs.syft-docker-image-tag }} ${{ inputs.docker-image-repo-tag }} > sbom-report.txt
        echo "Current SBOM for image"
        grep -A9999 'NAME' sbom-report.txt > sbom-report-table.txt
        rm -f sbom-report.txt

        echo "|Dependency|Version|Type|" >> simple-sbom-report.md
        echo "|---|---|----|" >> simple-sbom-report.md

        records=()
        while read line; do
          line=${line// /_}
          line=$(echo ${line} | sed 's/_\+/ /g')
          if [ -n "$line" ]; then
              dep=$(echo "$line" | awk '{print $1}')
              ver=$(echo "$line" | awk '{print $2}')
              typ=$(echo "$line" | awk '{print $3}')

              if [ "${typ}" == "" ]; then
                typ=${ver}
                ver=""
              fi

              if [ "${dep}" == "NAME" ]; then
                continue
              fi

              echo "|${dep}|${ver}|${typ}|" >> simple-sbom-report.md

              recordJson=$(jq -c -n --arg dep "${dep}" --arg ver "${ver}" --arg typ "$typ" \
                '{"dependency": $dep, "version": $ver, "type": $typ}')
              records+=(recordJson)
              echo "${recordJson}" >> records.txt
          fi
        done <sbom-report-table.txt
        
        rm -f sbom-report-table.txt

        if (( ${#records[@]} > 0 )); then
          cat records.txt | jq -s '.'
          rm -f records.txt
        fi
        
        SBOM_VALUE=$(cat simple-sbom-report.md)
        echo "sbom-report-file-path=simple-sbom-report.md" >> $GITHUB_OUTPUT

        echo 'sbom-report-value<<EOF' >> $GITHUB_OUTPUT
        cat simple-sbom-report.md >> $GITHUB_OUTPUT
        echo 'EOF' >> $GITHUB_OUTPUT

        cat simple-sbom-report.md >> $GITHUB_STEP_SUMMARY

    - name: Check SBOM for PR
      shell: bash
      run: |
        ls -la
        echo "SBOM report output"
        echo '${{ toJSON(steps.report-generator.outputs) }}' | jq

    - name: Report SBOM also in PR
      id: sbom-check
      if: ${{ inputs.add-comment-to-current-pr == 'true' }}
      shell: bash
      run: |
        if [ -f ${{ steps.report-generator.outputs.sbom-report-file-path }} ]; then
          cat ${{ steps.report-generator.outputs.sbom-report-file-path }}
          echo "sbom-generated=true" >> $GITHUB_OUTPUT

        else
          echo "sbom-generated=false" >> $GITHUB_OUTPUT
        fi

    - name: Add Docker SBOM PR Comment
      uses: seceng-devsecops-platform/marocchino-sticky-pull-request-comment-action@v2
      if: ${{ steps.sbom-check.outputs.sbom-generated == 'true' && inputs.add-comment-to-current-pr == 'true' }}
      with:
        header: sbom-report-${{ inputs.docker-image-repo-tag }}
        recreate: true
        path: ${{ steps.report-generator.outputs.sbom-report-file-path }}
