name: workflow-run-logs
description: Fetches the workflow run logs for a job or step 

author: vionix

branding:
  icon: anchor
  color: blue

inputs:
  github-org-repo:
    description: "The org/repo for the query"
    required: false
    default: ${{ github.repository }}
  workflow-run-id:
    description: "The ID of the workflow run from "
    required: true
  workflow-run-attempt-number:
    description: "The run attempt number for the execution"
    required: true
  filter-by-step-name:
    description: "The name of the step specified"
    required: false
  github-token:
    description: "The github token"
    required: true

outputs:
  log-content:
    description: "The contents of the log file"
    value: ${{ steps.parse-logs.outputs.content }}

runs:
  using: composite
    
  steps:
    - name: Download the logs from run from ${{ inputs.github-org-repo }}/actions/runs/${{ inputs.workflow-run-id }}/attemps/${{ inputs.workflow-run-attempt-number }}/logs
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        echo "Calling ${GITHUB_API_URL}/repos/${{ inputs.github-org-repo }}/actions/runs/${{ inputs.workflow-run-id }}/attemps/${{ inputs.workflow-run-attempt-number }}/logs"
        curl -L -H "Authorization: Bearer ${{ inputs.github-token }}" -o run.logs.zip ${GITHUB_API_URL}/repos/${{ inputs.github-org-repo }}/actions/runs/${{ inputs.workflow-run-id }}/attempts/${{ inputs.workflow-run-attempt-number }}/logs 

        ls -la run.logs.zip
        file run.logs.zip

        if [ -f run.logs.zip ]; then
          echo "Downloaded the zip file successfully..."
        else
          echo "Failed to download the logs for actions/runs/${{ inputs.workflow-run-id }}"
          exit 1
        fi

    - name: Unzip the downloaded zip file unzip run.logs
      shell: bash
      run: |
        echo "Unziping run.logs.zip"
        unzip run.logs.zip

    - name: Find the logs by Step name '${{ inputs.filter-by-step-name }}'
      id: parse-logs
      shell: bash
      run: |
        echo "Finding the file with the same '${{ inputs.filter-by-step-name }}'"
        find . -name "*${{ inputs.filter-by-step-name }}*" -not -name "*Post*" -print0
        FILE_NAME=$(find . -name "*${{ inputs.filter-by-step-name }}*" -not -name "*Post*" -print0)
        echo "Attempt to find: '${FILE_NAME}'"

        if [ "${FILE_NAME}" != '' ]; then
          cat "${FILE_NAME}" > log-content
          echo "Current logs content --------"
          cat log-content
          echo "--------------"
          CONTENT=$(cat log-content)
          echo "content=$CONTENT" >> $GITHUB_OUTPUT
        fi
